DROP TABLE STUDENT_COURSES;
DROP TABLE STD;
DROP TABLE ECOURSE;

CREATE TABLE STD (
  ID      INT PRIMARY KEY,
  NAME    VARCHAR(50),
  FAMILY  VARCHAR(50),
  AVERAGE FLOAT
);

CREATE TABLE ECOURSE (
  ID   INT PRIMARY KEY,
  NAME VARCHAR(50)
);

CREATE TABLE STUDENT_COURSES (
  STD_ID    INT FOREIGN KEY REFERENCES STD (ID),
  COURSE_ID INT FOREIGN KEY REFERENCES ECOURSE (ID),
  GRADE     FLOAT,
  PRIMARY KEY (STD_ID, COURSE_ID)
);

INSERT INTO STD VALUES (0, 'siavash', 'kavousi', 0)

INSERT INTO ECOURSE VALUES (0, 'DB')
INSERT INTO ECOURSE VALUES (1, 'OS')

INSERT INTO STUDENT_COURSES VALUES (0, 0, 18)
INSERT INTO STUDENT_COURSES VALUES (0, 1, 19.31)

SELECT *
FROM STUDENT_COURSES

CREATE PROCEDURE COMPUTE_STUDENT_AVG(@STUDENT_ID INT) AS 
    BEGIN 
      DECLARE @AVG FLOAT, @TOTAL FLOAT, @TEMP FLOAT, @COUNTER INT, @GRADE_CURSOR CURSOR
      SET @GRADE_CURSOR = CURSOR FOR SELECT GRADE
                          FROM STUDENT_COURSES
      OPEN @GRADE_CURSOR
      FETCH NEXT FROM @GRADE_CURSOR
      INTO @TOTAL
      SET @COUNTER = 1
      WHILE @@FETCH_STATUS = 0
        BEGIN
          FETCH NEXT FROM @GRADE_CURSOR
          INTO @TEMP
          SET @COUNTER = @COUNTER + 1
          SET @TOTAL = @TOTAL + @TEMP
        END
      SET @AVG = @TOTAL / @COUNTER
      CLOSE @GRADE_CURSOR
      DEALLOCATE @GRADE_CURSOR
      UPDATE STD
      SET AVERAGE = @AVG
      WHERE ID = @STUDENT_ID
    END

GO

EXECUTE COMPUTE_STUDENT_AVG 1

SELECT *
FROM STD