CREATE PROCEDURE GENERATE_EVEN_NUMBERS(@FIRST INT, @END INT) AS
  BEGIN
    SET @FIRST = @FIRST + @FIRST % 2
    WHILE @FIRST <= @END
      BEGIN
        PRINT @FIRST
        SET @FIRST = @FIRST + 2
      END
  END

GO

EXECUTE GENERATE_EVEN_NUMBERS 21, 31


CREATE PROCEDURE INSERT_EMPLOYEE(@NAME VARCHAR(50), @SALARY INT, @DEPTNO INT) AS
  BEGIN
    INSERT INTO EMP (NAME, SALARY, DEPTNO) VALUES (@NAME, @SALARY, @DEPTNO)
  END

GO

EXECUTE INSERT_EMPLOYEE 'Soroush', 290000, 6


CREATE PROCEDURE DELETE_EMPLOYEE(@EMP_ID INT) AS
  BEGIN
    DELETE FROM EMP
    WHERE EMP_ID = @EMP_ID
  END

GO

EXECUTE DELETE_EMPLOYEE 2


CREATE PROCEDURE UPDATE_EMPLOYEE(@EMP_ID INT, @NAME VARCHAR(50), @SALARY INT, @DEPTNO INT) AS
  BEGIN
    UPDATE EMP
    SET NAME = @NAME, SALARY = @SALARY, DEPTNO = @DEPTNO
    WHERE EMP_ID = @EMP_ID
  END

GO

EXECUTE UPDATE_EMPLOYEE 4, 'naghi', 12024, 2


CREATE PROCEDURE SELECT_EMPLOYEE_BETWEEN(@FIRST CHAR = 'a', @END CHAR = 'z') AS
  BEGIN
    SELECT *
    FROM EMP
    WHERE LEFT(NAME, 1) BETWEEN @FIRST AND @END
  END

GO

EXECUTE SELECT_EMPLOYEE_BETWEEN 'h', 'n'


CREATE PROCEDURE SELECT_DATE_INTERVAL(@FIRST_DATE VARCHAR(10), @END_DATE VARCHAR(10)) AS
  BEGIN
    SELECT
      P_ID,
      DATE1
    FROM G2Q1
    WHERE DATE1 BETWEEN @FIRST_DATE AND @END_DATE
  END

GO

EXECUTE SELECT_DATE_INTERVAL '1388/07/22', '1389/10/22'


CREATE PROCEDURE SELECT_BASED_ON_CONDITION(@INPUT INT) AS
  BEGIN
    IF @INPUT = 811
      BEGIN
        SELECT '1388 FARVARDIN'
      END
    ELSE IF @INPUT = 841
      BEGIN
        SELECT '1388 TIR'
      END
    ELSE IF @INPUT = 861
      BEGIN
        SELECT '1388 SHAHRIVAR'
      END
  END

GO

EXECUTE SELECT_BASED_ON_CONDITION 811

EXECUTE SELECT_BASED_ON_CONDITION 841

EXECUTE SELECT_BASED_ON_CONDITION 861


CREATE VIEW DISTINCT_FAMILY_NAME AS
  SELECT DISTINCT LNAME
  FROM EMP_TABLE

SELECT LNAME
FROM DISTINCT_FAMILY_NAME
ORDER BY LEN(LNAME)


CREATE PROCEDURE ERROR_HANDLER AS
  SET NOCOUNT ON;

  DECLARE @ERRORMESSAGE NVARCHAR(4000);
  DECLARE @ERRORSEVERITY INT;
  DECLARE @ERRORSTATE INT;

  SELECT
    @ERRORMESSAGE = ERROR_MESSAGE(),
    @ERRORSEVERITY = ERROR_SEVERITY(),
    @ERRORSTATE = ERROR_STATE();

  RAISERROR (@ERRORMESSAGE, -- Message text.
  @ERRORSEVERITY, -- Severity.
  @ERRORSTATE -- State.
  );

GO


BEGIN TRY

  SELECT EMP.SALARY / 0
  FROM EMP
  JOIN DEPT ON EMP.DEPTNO = DEPT.DEPTNO;

END TRY
BEGIN CATCH

  EXEC ERROR_HANDLER;

END CATCH