CREATE TABLE STUDENT (
  ID      INT PRIMARY KEY IDENTITY,
  NAME    VARCHAR(50),
  FAMILY  VARCHAR(50),
  AVERAGE FLOAT
);

CREATE TABLE COURSE (
  ID   INT PRIMARY KEY IDENTITY,
  NAME VARCHAR(50)
)

CREATE TABLE TAKES (
  STD_ID    INT FOREIGN KEY REFERENCES STUDENT (ID),
  COURSE_ID INT FOREIGN KEY REFERENCES COURSE (ID),
  GRADE     FLOAT,
  PRIMARY KEY (STD_ID, COURSE_ID)
)


CREATE FUNCTION IS_PRIME_NUMBER(@NUMBER INT)
  RETURNS BIT AS
  BEGIN
    DECLARE @DIVISOR INT
    SET @DIVISOR = 2
    IF (@NUMBER >= 2)
      WHILE @DIVISOR < @NUMBER
        BEGIN
          IF @NUMBER % @DIVISOR != 0
            RETURN 0
        END
    ELSE
      RETURN 0
    RETURN 1
  END

GO

INSERT INTO STUDENT VALUES ('mehdi', 'seyed', 18)
INSERT INTO STUDENT VALUES ('siavash', 'kavousi', 19)

SELECT *
FROM STUDENT

SELECT *
FROM STUDENT
WHERE dbo.IS_PRIME_NUMBER(ID) != 0

CREATE TRIGGER PREVENT_INSERTION
  ON STUDENT
  INSTEAD OF INSERT AS
  BEGIN
    PRINT 'no change was done!'
  END

INSERT INTO STUDENT VALUES ('ansar', 'rashti', 10)