CREATE DATABASE FLIGHT;

DROP TABLE TICKET
DROP TABLE RESERVE

CREATE TABLE RESERVE (
  FLIGHT_NO   INT,
  FLIGHT_DATE DATETIME,
  SOURCE      VARCHAR(50),
  TARGET      VARCHAR(50),
  CAPACITY    SMALLINT,
  NUMBER      SMALLINT,
  PRIMARY KEY (FLIGHT_NO, FLIGHT_DATE)
);

CREATE TABLE TICKET (
  TICKET_NO   VARCHAR(50) PRIMARY KEY,
  PASS_NO     VARCHAR(50),
  FLIGHT_NAME VARCHAR(50),
  L_NAME      VARCHAR(50),
  FLIGHT_NO   INT,
  FLIGHT_DATE DATETIME,
  FOREIGN KEY (FLIGHT_NO, FLIGHT_DATE) REFERENCES RESERVE (FLIGHT_NO, FLIGHT_DATE)
);

INSERT INTO RESERVE VALUES (0, '1998-02-23 14:23:05', 'Tehran', 'Berlin', 500, 0)
INSERT INTO RESERVE VALUES (1, '2016-02-23 14:23:05', 'Tehran', 'Rio', 500, 0)

SELECT *
FROM RESERVE

SELECT *
FROM TICKET

ALTER PROCEDURE RESERVE_TICKET(@TICKET_NO VARCHAR(50), @PASS_NO VARCHAR(50), @FLIGHT_NAME VARCHAR(50),
                               @L_NAME    VARCHAR(50), @FLIGHT_NO INT, @FLIGHT_DATE DATETIME) AS
BEGIN
  BEGIN TRANSACTION
  BEGIN TRY
  INSERT INTO TICKET VALUES (@TICKET_NO, @PASS_NO, @FLIGHT_NAME, @L_NAME, @FLIGHT_NO, @FLIGHT_DATE)
  UPDATE RESERVE
  SET NUMBER = NUMBER + 1
  WHERE FLIGHT_NO = @FLIGHT_NO AND FLIGHT_DATE = @FLIGHT_DATE
  COMMIT TRANSACTION
  END TRY
  BEGIN CATCH
    PRINT 'Reservation process failed'
    ROLLBACK TRANSACTION
  END CATCH
END

GO

EXECUTE RESERVE_TICKET '2', '5521', '1', 'TEHBER', 0, '1998-02-23 14:23:05'

ALTER PROCEDURE CANCEL_TICKET(@TICKET_NO VARCHAR(50), @FLIGHT_NO INT, @FLIGHT_DATE DATETIME) AS
BEGIN
  BEGIN TRANSACTION
  BEGIN TRY
  IF ((SELECT count(TICKET_NO)
       FROM TICKET) > 0)
    BEGIN
      DELETE FROM TICKET
      WHERE TICKET_NO = @TICKET_NO
      UPDATE RESERVE
      SET NUMBER = NUMBER - 1
      WHERE FLIGHT_NO = @FLIGHT_NO AND FLIGHT_DATE = @FLIGHT_DATE
      COMMIT TRANSACTION
    END
  ELSE
    BEGIN
      ROLLBACK TRANSACTION
    END
  END TRY
  BEGIN CATCH
    PRINT 'process ticket cancelling failed'
    ROLLBACK TRANSACTION
  END CATCH
END

GO

EXECUTE CANCEL_TICKET '2', 0, '1998-02-23 14:23:05'